# Code generated by clrinf-codegen. DO NOT EDIT.
defmodule ClrInf.Contracts.Common.RecordV1 do
  @moduledoc """
  CloudEvent payload for RecordV1
  """
  @event_type "test.Record.v1"

  @enforce_keys [
    :display_name,
    :enabled,
    :nested,
    :payload,
    :type,
  ]

  defstruct [
    display_name: nil,
    enabled: nil,
    nested: nil,
    payload: nil,
    type: nil,
    count: nil,
    ratio: nil,
    records: nil
  ]

  @type t :: %__MODULE__{
    display_name: String.t(),
    enabled: boolean(),
    nested: list(list(integer())),
    payload: map(),
    type: String.t(),
    count: integer() | nil,
    ratio: float() | nil,
    records: list(map()) | nil
  }
  @doc "Returns the standard CloudEvents event type string."
  @spec event_type() :: String.t()
  def event_type, do: @event_type

  @doc "Parses a CloudEvent data payload map into an idiomatic struct."
  @spec from_map(map()) :: {:ok, t()} | {:error, String.t()}
  def from_map(attrs) when is_map(attrs) do
    fields = [
      { "displayName", :display_name },
      { "enabled", :enabled },
      { "nested", :nested },
      { "payload", :payload },
      { "type", :type },
      { "count", :count },
      { "ratio", :ratio },
      { "records", :records }
    ]
    values = for {wire, key} <- fields, Map.has_key?(attrs, wire) or Map.has_key?(attrs, key),
      into: %{}, do: {key, Map.get(attrs, wire, Map.get(attrs, key))}
    missing = Enum.reject(@enforce_keys, &Map.has_key?(values, &1))
    if missing == [], do: {:ok, struct!(__MODULE__, values)},
      else: {:error, "Missing required fields: #{inspect(missing)}"}
  end

  def from_map(_attrs), do: {:error, "Expected a map"}

  def to_map(%__MODULE__{} = value) do
    %{
      "displayName" => value.display_name,
      "enabled" => value.enabled,
      "nested" => value.nested,
      "payload" => value.payload,
      "type" => value.type,
      "count" => value.count,
      "ratio" => value.ratio,
      "records" => value.records
    }
    |> Enum.reject(fn {_key, value} -> is_nil(value) end)
    |> Map.new()
  end
  @doc "Builds a CloudEvents map with caller-supplied identity and context. Validate at the boundary."
  @spec to_cloudevent(t(), keyword()) :: map()
  def to_cloudevent(%__MODULE__{} = struct_data, opts \\ []) do
    tenant_id = Keyword.fetch!(opts, :tenant_id)
    correlation_id = Keyword.fetch!(opts, :correlation_id)
    causation_id = Keyword.fetch!(opts, :causation_id)
    subject = Keyword.get(opts, :subject, "clrinf/common/#{Keyword.fetch!(opts, :id)}")

    %{
      "specversion" => "1.0",
      "id" => Keyword.fetch!(opts, :id),
      "source" => "clrinf/common",
      "type" => "test.Record.v1",
      "subject" => subject,
      "time" => DateTime.utc_now() |> DateTime.to_iso8601(),
      "datacontenttype" => "application/json",
      "tenantid" => tenant_id,
      "correlationid" => correlation_id,
      "causationid" => causation_id,
      "data" => to_map(struct_data)
    }
  end
end
