// <auto-generated>
// Code generated by clrinf-codegen. DO NOT EDIT.
// </auto-generated>

#nullable enable

namespace ClrInf.Contracts.Kampanya;

using ClrInf.Contracts;

/// <summary>
/// Müşterilere ve siparişe açık aktif kampanyaları listeleme sorgusu.
/// </summary>
public sealed record AktifKampanyalarV1(
    /// <summary>Kategoriye özel kampanyaları filtreleme (isteğe bağlı)</summary>
    string? HedefKategori = null
)
{
    public const string QueryTypeName = "com.clrinf.kampanya.AktifKampanyalar.v1";
    public string QueryType => QueryTypeName;
}
