// <auto-generated>
// Code generated by clrinf-codegen. DO NOT EDIT.
// </auto-generated>

#nullable enable

namespace ClrInf.Contracts.Auth;

using ClrInf.Contracts;

/// <summary>
/// Command requesting identity authentication with credentials.
/// </summary>
public sealed record AuthenticateUserCommandV1(
    /// <summary>Plain text password for verification</summary>
    string Password,
    /// <summary>User username or email</summary>
    string Username,
    /// <summary>Optional OAuth2 client ID</summary>
    string? ClientId = null
)
{
    public const string CommandTypeName = "com.clrinf.auth.AuthenticateUser.v1";
    public string CommandType => CommandTypeName;
}
