// <auto-generated>
// Code generated by clrinf-codegen. DO NOT EDIT.
// </auto-generated>

#nullable enable

namespace ClrInf.Contracts.Katalog;

using ClrInf.Contracts;

/// <summary>
/// Bir ürünün birim fiyatı güncellendiğinde yayımlanan olay.
/// </summary>
public sealed record FiyatGuncellendiV1(
    /// <summary>Fiyatı güncelleyen kullanıcı ID</summary>
    string DegistirenKullanici,
    /// <summary>Önceki birim fiyatı</summary>
    double EskiFiyat,
    /// <summary>Para birimi kodu (ISO 4217)</summary>
    string ParaBirimi,
    /// <summary>Stok tutma birimi kodu</summary>
    string Sku,
    /// <summary>Güncel birim fiyatı</summary>
    double YeniFiyat,
    DateTimeOffset? GecerlilikBaslangic = null,
    DateTimeOffset? GecerlilikBitis = null,
    /// <summary>Değişiklik gerekçesi</summary>
    string? Gerekce = null
) : ICloudEvent
{
    public const string EventTypeName = "com.clrinf.katalog.FiyatGuncellendi.v1";
    public string EventType => EventTypeName;
}
