// <auto-generated>
// Code generated by clrinf-codegen. DO NOT EDIT.
// </auto-generated>

#nullable enable

namespace ClrInf.Contracts.Stok;

using ClrInf.Contracts;

/// <summary>
/// Query requesting current available stock quantity for a specific SKU.
/// </summary>
public sealed record GetStockAvailabilityQueryV1(
    /// <summary>Stock keeping unit code</summary>
    string Sku,
    /// <summary>Optional warehouse filter</summary>
    string? Warehouse = null
)
{
    public const string QueryTypeName = "com.clrinf.stok.GetStockAvailability.v1";
    public string QueryType => QueryTypeName;
}
