// <auto-generated>
// Code generated by clrinf-codegen. DO NOT EDIT.
// </auto-generated>

#nullable enable

namespace ClrInf.Contracts.Oms;

using ClrInf.Contracts;

/// <summary>
/// Teslim edilmiş bir sipariş için müşteri RMA iade talebi oluşturma komutu.
/// </summary>
public sealed record IadeTalebiOlusturV1(
    string IadeNedeni,
    string SiparisId,
    IReadOnlyList<string>? IadeEdilecekSkular = null
)
{
    public const string CommandTypeName = "com.clrinf.oms.IadeTalebiOlustur.v1";
    public string CommandType => CommandTypeName;
}
