// <auto-generated>
// Code generated by clrinf-codegen. DO NOT EDIT.
// </auto-generated>

#nullable enable

namespace ClrInf.Contracts.Kampanya;

using ClrInf.Contracts;

/// <summary>
/// Yeni bir pazarlama kampanyası veya indirim kuralı tanımlama komutu. Cedar ABAC: MarketingLead veya Admin rolü gerektirir.
/// </summary>
public sealed record KampanyaOlusturV1(
    /// <summary>Geçerlilik başlangıç tarihi (ISO 8601 UTC)</summary>
    DateTimeOffset BaslangicTarihi,
    /// <summary>Kampanya başlığı ve promosyon metni</summary>
    string Baslik,
    /// <summary>İndirim değeri (yüzde ise 0.15 = %15, sabit tutar ise dolar/TL tutarı)</summary>
    double Deger,
    /// <summary>Kampanya benzersiz kodu (örn: YAZ2026, SENSOR15)</summary>
    string Kod,
    /// <summary>İndirim hesaplama türü</summary>
    string Tur,
    /// <summary>Kampanya koşulları ve detaylı açıklama</summary>
    string? Aciklama = null,
    /// <summary>Geçerlilik bitiş tarihi (ISO 8601 UTC)</summary>
    DateTimeOffset? BitisTarihi = null,
    /// <summary>Yalnızca belirli kategoriye uygulanacaksa kategori yolu</summary>
    string? HedefKategori = null,
    /// <summary>Toplam kampanya kullanım kotası (dolunca tükenir)</summary>
    int? MaksimumKullanimSayisi = null,
    /// <summary>Kampanyanın geçerli olması için gereken minimum sepet tutarı</summary>
    double? MinimumSepetTutari = null
)
{
    public const string CommandTypeName = "com.clrinf.kampanya.KampanyaOlustur.v1";
    public string CommandType => CommandTypeName;
}
