// <auto-generated>
// Code generated by clrinf-codegen. DO NOT EDIT.
// </auto-generated>

#nullable enable

namespace ClrInf.Contracts.Kampanya;

using ClrInf.Contracts;

/// <summary>
/// Rust Kural Motoruna çoklu sepet kalemleri ve talep edilen kampanyaları göndererek optimum indirim çözümleme sözleşmesi.
/// </summary>
public sealed record KampanyaHesaplaV1(
    IReadOnlyList<string> Kalemler,
    string SepetId,
    double SepetTutari,
    /// <summary>Uygulanmak istenen kampanya kodları listesi</summary>
    IReadOnlyList<string> TalepEdilenKampanyalar,
    string? KullaniciId = null
)
{
    public const string QueryTypeName = "com.clrinf.kampanya.KampanyaHesapla.v1";
    public string QueryType => QueryTypeName;
}
