// <auto-generated>
// Code generated by clrinf-codegen. DO NOT EDIT.
// </auto-generated>

#nullable enable

namespace ClrInf.Contracts.Kampanya;

using ClrInf.Contracts;

/// <summary>
/// Mevcut bir kampanyayı aktifleştirme veya durdurma komutu.
/// </summary>
public sealed record KampanyaDurumGuncelleV1(
    /// <summary>Yeni durum (true: aktif, false: pasif)</summary>
    bool Aktif,
    /// <summary>Kampanya kodu</summary>
    string Kod,
    /// <summary>Durum değişikliği gerekçesi</summary>
    string? Gerekce = null
)
{
    public const string CommandTypeName = "com.clrinf.kampanya.KampanyaDurumGuncelle.v1";
    public string CommandType => CommandTypeName;
}
