// <auto-generated>
// Code generated by clrinf-codegen. DO NOT EDIT.
// </auto-generated>

#nullable enable

namespace ClrInf.Contracts.Kampanya;

using ClrInf.Contracts;

/// <summary>
/// Belirli bir kampanyanın kullanım kotası ve kural detaylarını sorgulama.
/// </summary>
public sealed record KampanyaDetayiV1(
    string Kod
)
{
    public const string QueryTypeName = "com.clrinf.kampanya.KampanyaDetayi.v1";
    public string QueryType => QueryTypeName;
}
