// <auto-generated>
// Code generated by clrinf-codegen. DO NOT EDIT.
// </auto-generated>

#nullable enable

namespace ClrInf.Contracts.Kampanya;

using ClrInf.Contracts;

/// <summary>
/// Yeni bir kampanya tanımlandığında yayımlanan CloudEvent.
/// </summary>
public sealed record KampanyaOlusturulduV1(
    string Baslik,
    double Deger,
    string Kod,
    string OlusturanKullanici,
    DateTimeOffset OlusturulmaZamani,
    string Tur,
    string? HedefKategori = null,
    long? MaksimumKullanimSayisi = null,
    double? MinimumSepetTutari = null
) : ICloudEvent
{
    public const string EventTypeName = "com.clrinf.kampanya.KampanyaOlusturuldu.v1";
    public string EventType => EventTypeName;
}
