// <auto-generated>
// Code generated by clrinf-codegen. DO NOT EDIT.
// </auto-generated>

#nullable enable

namespace ClrInf.Contracts.Kampanya;

using ClrInf.Contracts;

/// <summary>
/// Birleştirilebilir (Stackable) ve Münhasır (Exclusive) kuralları içeren yeni kampanya oluşturma komutu.
/// </summary>
public sealed record KampanyaOlusturV2(
    DateTimeOffset BaslangicTarihi,
    string Baslik,
    /// <summary>true: Diğer izinli kampanyalarla birleşebilir; false: Münhasırdır (Exclusive), sepette tek başına uygulanır</summary>
    bool Birlestirilebilir,
    double Deger,
    /// <summary>Kampanya benzersiz kodu</summary>
    string Kod,
    string Tur,
    string? Aciklama = null,
    /// <summary>Birleştirme kapsamı</summary>
    string? BirlestirmeTuru = null,
    DateTimeOffset? BitisTarihi = null,
    /// <summary>Bu kampanyanın etiketleri</summary>
    IReadOnlyList<string>? Etiketler = null,
    string? HedefKategori = null,
    /// <summary>Birleşebileceği etiketler (örn: ['SADAKAT', 'SEZON'])</summary>
    IReadOnlyList<string>? IzinliEtiketler = null,
    /// <summary>Yalnızca bu kodlara sahip kampanyalarla birleşebilir</summary>
    IReadOnlyList<string>? IzinliKampanyaKodlari = null,
    int? MaksimumKullanimSayisi = null,
    double? MinimumSepetTutari = null,
    /// <summary>Çoklu indirim uygulama önceliği (1: Önce ürün indirimi, 2: Kalan tutar üzerinden sepet indirimi)</summary>
    long? UygulamaSirasi = null,
    /// <summary>Birlikte uygulanamayacak etiketler (örn: ['FLAS_INDIRIM'])</summary>
    IReadOnlyList<string>? YasakliEtiketler = null
)
{
    public const string CommandTypeName = "com.clrinf.kampanya.KampanyaOlustur.v2";
    public string CommandType => CommandTypeName;
}
