// <auto-generated>
// Code generated by clrinf-codegen. DO NOT EDIT.
// </auto-generated>

#nullable enable

namespace ClrInf.Contracts.Kampanya;

using ClrInf.Contracts;

/// <summary>
/// Bir sepet veya siparişe kampanya indirimi başarıyla uygulandığında yayımlanan CloudEvent.
/// </summary>
public sealed record KampanyaUygulandiV1(
    double IndirimTutari,
    long KalanKullanimKotasi,
    string Kod,
    string SepetId,
    DateTimeOffset UygulanmaZamani,
    string? KullaniciId = null
) : ICloudEvent
{
    public const string EventTypeName = "com.clrinf.kampanya.KampanyaUygulandi.v1";
    public string EventType => EventTypeName;
}
