// <auto-generated>
// Code generated by clrinf-codegen. DO NOT EDIT.
// </auto-generated>

#nullable enable

namespace ClrInf.Contracts.Kampanya;

using ClrInf.Contracts;

/// <summary>
/// Sepetteki ürünlere belirli bir kampanyayı uygulayarak indirim tutarını kesinleştirme komutu.
/// </summary>
public sealed record KampanyaUygulaV1(
    string KampanyaKodu,
    string SepetId,
    double SepetTutari,
    IReadOnlyList<string>? Kalemler = null,
    string? KullaniciId = null
)
{
    public const string CommandTypeName = "com.clrinf.kampanya.KampanyaUygula.v1";
    public string CommandType => CommandTypeName;
}
