// <auto-generated>
// Code generated by clrinf-codegen. DO NOT EDIT.
// </auto-generated>

#nullable enable

namespace ClrInf.Contracts.Kampanya;

using ClrInf.Contracts;

/// <summary>
/// Kampanyanın maksimum kullanım kotası veya bütçesi tükendiğinde yayımlanan CloudEvent.
/// </summary>
public sealed record KampanyaTukendiV1(
    string Kod,
    long ToplamKullanimSayisi,
    DateTimeOffset TukenmeZamani
) : ICloudEvent
{
    public const string EventTypeName = "com.clrinf.kampanya.KampanyaTukendi.v1";
    public string EventType => EventTypeName;
}
