// <auto-generated>
// Code generated by clrinf-codegen. DO NOT EDIT.
// </auto-generated>

#nullable enable

namespace ClrInf.Contracts.Katalog;

using ClrInf.Contracts;

/// <summary>
/// Katalog ürün listesi sorgusu — kategori filtreleme ve sayfalama destekli.
/// </summary>
public sealed record KatalogListesiV1(
    /// <summary>Ürün adı veya SKU üzerinde metin arama (isteğe bağlı)</summary>
    string? AramaMetni = null,
    /// <summary>Filtrelenecek kategori yolu (isteğe bağlı)</summary>
    string? KategoriYolu = null,
    /// <summary>Yalnızca stokta bulunan ürünler listelensin mi?</summary>
    bool? SadeceMüsaitUrunler = null,
    /// <summary>Sayfa numarası</summary>
    int? Sayfa = null,
    /// <summary>Sayfa başına sonuç sayısı</summary>
    int? SayfaBoyutu = null
)
{
    public const string QueryTypeName = "com.clrinf.katalog.KatalogListesi.v1";
    public string QueryType => QueryTypeName;
}
