// <auto-generated>
// Code generated by clrinf-codegen. DO NOT EDIT.
// </auto-generated>

#nullable enable

namespace ClrInf.Contracts.Eticaret;

using ClrInf.Contracts;

/// <summary>
/// Sepete promosyon veya indirim kuponu uygulama komutu.
/// </summary>
public sealed record KuponUygulaV1(
    /// <summary>Uygulanacak indirim/kupon kodu (örn: YAZ2026, VIP50)</summary>
    string KuponKodu,
    /// <summary>Sepet benzersiz kimliği</summary>
    string SepetId
)
{
    public const string CommandTypeName = "com.clrinf.eticaret.KuponUygula.v1";
    public string CommandType => CommandTypeName;
}
