// <auto-generated>
// Code generated by clrinf-codegen. DO NOT EDIT.
// </auto-generated>

#nullable enable

namespace ClrInf.Contracts.Eticaret;

using ClrInf.Contracts;

/// <summary>
/// Checkout iş akışı başlatıldığında ve sepet kilitlendiğinde yayımlanan olay.
/// </summary>
public sealed record OdemeBasladiV1(
    DateTimeOffset BaslangicZamani,
    string ParaBirimi,
    /// <summary>Kilitlenen sepet ID</summary>
    string SepetId,
    /// <summary>Oluşturulacak sipariş ID</summary>
    string SiparisId,
    double TahsilEdilecekTutar
) : ICloudEvent
{
    public const string EventTypeName = "com.clrinf.eticaret.OdemeBasladi.v1";
    public string EventType => EventTypeName;
}
