// <auto-generated>
// Code generated by clrinf-codegen. DO NOT EDIT.
// </auto-generated>

#nullable enable

namespace ClrInf.Contracts.Eticaret;

using ClrInf.Contracts;

/// <summary>
/// Sepetteki ürünler için 5 adımlı OdemeSaga iş akışını başlatan checkout komutu.
/// </summary>
public sealed record OdeV1(
    /// <summary>Tekrarlı istekleri engelleyen benzersiz correlation ID</summary>
    string KorelasyonId,
    /// <summary>Ödeme yöntemi (KREDI_KARTI, HAVALE, CARI)</summary>
    string OdemeYontemi,
    /// <summary>Ödemesi yapılacak kilitlenecek sepet ID</summary>
    string SepetId,
    /// <summary>Sipariş teslimat adresi</summary>
    string TeslimatAdresi,
    /// <summary>Telafi edici işlem testi için ödeme adımını başarısız yapma bayrağı</summary>
    bool? OdemeHatasiniSimuleEt = null
)
{
    public const string CommandTypeName = "com.clrinf.eticaret.Ode.v1";
    public string CommandType => CommandTypeName;
}
