// <auto-generated>
// Code generated by clrinf-codegen. DO NOT EDIT.
// </auto-generated>

#nullable enable

namespace ClrInf.Contracts.Auth;

using ClrInf.Contracts;

/// <summary>
/// Event emitted when an authorization policy (Cedar/ABAC) is created or modified.
/// </summary>
public sealed record PolicyUpdatedV1(
    /// <summary>Policy identifier</summary>
    string PolicyId,
    /// <summary>Human-readable policy name</summary>
    string PolicyName,
    /// <summary>Update timestamp</summary>
    DateTimeOffset UpdatedAt,
    /// <summary>Incremented policy version</summary>
    long Version
) : ICloudEvent
{
    public const string EventTypeName = "com.clrinf.auth.PolicyUpdated.v1";
    public string EventType => EventTypeName;
}
