// <auto-generated>
// Code generated by clrinf-codegen. DO NOT EDIT.
// </auto-generated>

#nullable enable

namespace ClrInf.Contracts.Stok;

using ClrInf.Contracts;

/// <summary>
/// Command instructing the inventory service to release previously reserved stock (compensating action).
/// </summary>
public sealed record ReleaseStockCommandV1(
    /// <summary>Identifier of the order to release</summary>
    string OrderId,
    /// <summary>Quantity to release</summary>
    int Quantity,
    /// <summary>Reason for cancellation/release</summary>
    string Reason,
    /// <summary>Stock keeping unit code</summary>
    string Sku
)
{
    public const string CommandTypeName = "com.clrinf.stok.ReleaseStock.v1";
    public string CommandType => CommandTypeName;
}
