// <auto-generated>
// Code generated by clrinf-codegen. DO NOT EDIT.
// </auto-generated>

#nullable enable

namespace ClrInf.Contracts.Stok;

using ClrInf.Contracts;

/// <summary>
/// Command instructing the inventory service to reserve stock for an order.
/// </summary>
public sealed record ReserveStockCommandV1(
    /// <summary>Identifier of the order</summary>
    string OrderId,
    /// <summary>Quantity to reserve</summary>
    int Quantity,
    /// <summary>Stock keeping unit code</summary>
    string Sku,
    /// <summary>Optional preferred warehouse code</summary>
    string? PreferredWarehouse = null
)
{
    public const string CommandTypeName = "com.clrinf.stok.ReserveStock.v1";
    public string CommandType => CommandTypeName;
}
