// <auto-generated>
// Code generated by clrinf-codegen. DO NOT EDIT.
// </auto-generated>

#nullable enable

namespace ClrInf.Contracts.Eticaret;

using ClrInf.Contracts;

/// <summary>
/// Kullanıcının sepetine ürün kalemi ekleme veya miktar artırma komutu.
/// </summary>
public sealed record SepeteEkleV1(
    /// <summary>Ekleme anındaki birim satış fiyatı</summary>
    double BirimFiyat,
    /// <summary>Eklenecek adet</summary>
    int Miktar,
    /// <summary>Sepet benzersiz kimliği</summary>
    string SepetId,
    /// <summary>Eklenecek ürün stok tutma birimi</summary>
    string Sku,
    /// <summary>Müşteri veya misafir oturum kimliği</summary>
    string? KullaniciId = null
)
{
    public const string CommandTypeName = "com.clrinf.eticaret.SepeteEkle.v1";
    public string CommandType => CommandTypeName;
}
