// <auto-generated>
// Code generated by clrinf-codegen. DO NOT EDIT.
// </auto-generated>

#nullable enable

namespace ClrInf.Contracts.Eticaret;

using ClrInf.Contracts;

/// <summary>
/// Kullanıcının sepetinden ürün çıkarma veya miktar azaltma komutu.
/// </summary>
public sealed record SepettenCikarV1(
    /// <summary>Sepet benzersiz kimliği</summary>
    string SepetId,
    /// <summary>Çıkarılacak ürün stok kodu</summary>
    string Sku,
    /// <summary>Eğer belirtilmişse eksiltilecek adet, boşsa tamamen çıkarır</summary>
    int? Miktar = null
)
{
    public const string CommandTypeName = "com.clrinf.eticaret.SepettenCikar.v1";
    public string CommandType => CommandTypeName;
}
