// <auto-generated>
// Code generated by clrinf-codegen. DO NOT EDIT.
// </auto-generated>

#nullable enable

namespace ClrInf.Contracts.Eticaret;

using ClrInf.Contracts;

/// <summary>
/// Sepet içeriği, kuponu veya toplam tutarı değiştiğinde yayımlanan olay.
/// </summary>
public sealed record SepetGuncellendiV1(
    double AraToplam,
    double GenelToplam,
    DateTimeOffset GuncellenmeTarihi,
    double IndirimTutari,
    IReadOnlyList<string> Kalemler,
    /// <summary>Sepet kimliği</summary>
    string SepetId,
    /// <summary>Müşteri ID</summary>
    string? KullaniciId = null,
    /// <summary>Uygulanan kupon</summary>
    string? KuponKodu = null
) : ICloudEvent
{
    public const string EventTypeName = "com.clrinf.eticaret.SepetGuncellendi.v1";
    public string EventType => EventTypeName;
}
