// <auto-generated>
// Code generated by clrinf-codegen. DO NOT EDIT.
// </auto-generated>

#nullable enable

namespace ClrInf.Contracts.Eticaret;

using ClrInf.Contracts;

/// <summary>
/// Sepet içeriği ve anlık fiyatlandırma sorgusu.
/// </summary>
public sealed record SepetDetayiV1(
    /// <summary>Sorgulanacak sepet ID</summary>
    string SepetId
)
{
    public const string QueryTypeName = "com.clrinf.eticaret.SepetDetayi.v1";
    public string QueryType => QueryTypeName;
}
