// <auto-generated>
// Code generated by clrinf-codegen. DO NOT EDIT.
// </auto-generated>

#nullable enable

namespace ClrInf.Contracts.Oms;

using ClrInf.Contracts;

/// <summary>
/// Sipariş durumu değiştiğinde yayımlanan CloudEvent.
/// </summary>
public sealed record SiparisDurumuDegistiV1(
    DateTimeOffset DegisimZamani,
    string EskiDurum,
    string SiparisId,
    string YeniDurum,
    string? DegistirenKullanici = null
) : ICloudEvent
{
    public const string EventTypeName = "com.clrinf.oms.SiparisDurumuDegisti.v1";
    public string EventType => EventTypeName;
}
