// <auto-generated>
// Code generated by clrinf-codegen. DO NOT EDIT.
// </auto-generated>

#nullable enable

namespace ClrInf.Contracts.Oms;

using ClrInf.Contracts;

/// <summary>
/// Sipariş kalemleri, kargo takibi ve durum geçmişi detay sorgusu.
/// </summary>
public sealed record SiparisDetayiV1(
    string SiparisId
)
{
    public const string QueryTypeName = "com.clrinf.oms.SiparisDetayi.v1";
    public string QueryType => QueryTypeName;
}
