// <auto-generated>
// Code generated by clrinf-codegen. DO NOT EDIT.
// </auto-generated>

#nullable enable

namespace ClrInf.Contracts.Oms;

using ClrInf.Contracts;

/// <summary>
/// Siparişin durumunu ilerletme komutu (HAZIRLANIYOR, PAKETLENDI, KARGODA, TESLIM_EDILDI). Cedar ABAC: WarehouseManager veya Admin rolü gerektirir.
/// </summary>
public sealed record SiparisDurumuGuncelleV1(
    string SiparisId,
    string YeniDurum,
    string? Aciklama = null,
    /// <summary>Kargo lojistik firması (örn: Yurtiçi, DHL)</summary>
    string? KargoFirmasi = null,
    /// <summary>KARGODA durumuna geçerken zorunlu kargo takip barkodu</summary>
    string? KargoTakipNo = null
)
{
    public const string CommandTypeName = "com.clrinf.oms.SiparisDurumuGuncelle.v1";
    public string CommandType => CommandTypeName;
}
