// <auto-generated>
// Code generated by clrinf-codegen. DO NOT EDIT.
// </auto-generated>

#nullable enable

namespace ClrInf.Contracts.Eticaret;

using ClrInf.Contracts;

/// <summary>
/// OdemeSaga hata ile karşılaştığında ve telafi edici işlemler çalıştırıldığında yayımlanan olay.
/// </summary>
public sealed record SiparisTelafiBekliyorV1(
    string HataKodu,
    string HataMesaji,
    string SepetId,
    string SiparisId,
    IReadOnlyList<string> TelafiEdilenAdimlar,
    DateTimeOffset? Zaman = null
) : ICloudEvent
{
    public const string EventTypeName = "com.clrinf.eticaret.SiparisTelafiBekliyor.v1";
    public string EventType => EventTypeName;
}
