// <auto-generated>
// Code generated by clrinf-codegen. DO NOT EDIT.
// </auto-generated>

#nullable enable

namespace ClrInf.Contracts.Eticaret;

using ClrInf.Contracts;

/// <summary>
/// 5 adımlı OdemeSaga başarıyla sonuçlandığında ve sipariş onaylandığında yayımlanan olay.
/// </summary>
public sealed record SiparisOlusturulduV1(
    DateTimeOffset OnayZamani,
    string ParaBirimi,
    string SepetId,
    string SiparisId,
    double ToplamTutar,
    string? OdemeReferansi = null
) : ICloudEvent
{
    public const string EventTypeName = "com.clrinf.eticaret.SiparisOlusturuldu.v1";
    public string EventType => EventTypeName;
}
