// <auto-generated>
// Code generated by clrinf-codegen. DO NOT EDIT.
// </auto-generated>

#nullable enable

namespace ClrInf.Contracts.Oms;

using ClrInf.Contracts;

/// <summary>
/// Onaylanmış veya hazırlık aşamasındaki bir siparişi iptal ederek rezerve/tahsisli stoğu geri yükleme komutu.
/// </summary>
public sealed record SiparisIptalEtV1(
    string IptalGerekcesi,
    string SiparisId,
    string? IptalEdenKullanici = null
)
{
    public const string CommandTypeName = "com.clrinf.oms.SiparisIptalEt.v1";
    public string CommandType => CommandTypeName;
}
