// <auto-generated>
// Code generated by clrinf-codegen. DO NOT EDIT.
// </auto-generated>

#nullable enable

namespace ClrInf.Contracts.Oms;

using ClrInf.Contracts;

/// <summary>
/// RMA İade talebi onaylanıp ürünler depoya geri girdiğinde yayımlanan CloudEvent.
/// </summary>
public sealed record SiparisIadeEdildiV1(
    double IadeTutari,
    string RmaKodu,
    string SiparisId,
    DateTimeOffset TamamlanmaZamani
) : ICloudEvent
{
    public const string EventTypeName = "com.clrinf.oms.SiparisIadeEdildi.v1";
    public string EventType => EventTypeName;
}
