// <auto-generated>
// Code generated by clrinf-codegen. DO NOT EDIT.
// </auto-generated>

#nullable enable

namespace ClrInf.Contracts.Oms;

using ClrInf.Contracts;

/// <summary>
/// Durum, müşteri veya tarih aralığına göre sipariş listeleme sorgusu.
/// </summary>
public sealed record SiparisListesiSorgulaV1(
    string? Durum = null,
    string? KullaniciId = null,
    long? Sayfa = null,
    long? SayfaBoyutu = null
)
{
    public const string QueryTypeName = "com.clrinf.oms.SiparisListesiSorgula.v1";
    public string QueryType => QueryTypeName;
}
