// <auto-generated>
// Code generated by clrinf-codegen. DO NOT EDIT.
// </auto-generated>

#nullable enable

namespace ClrInf.Contracts.Oms;

using ClrInf.Contracts;

/// <summary>
/// Sipariş kargoya verildiğinde ve takip barkodu üretildiğinde yayımlanan CloudEvent.
/// </summary>
public sealed record SiparisKargoyaVerildiV1(
    string KargoFirmasi,
    string KargoTakipNo,
    DateTimeOffset KargolanmaZamani,
    string SiparisId
) : ICloudEvent
{
    public const string EventTypeName = "com.clrinf.oms.SiparisKargoyaVerildi.v1";
    public string EventType => EventTypeName;
}
