// <auto-generated>
// Code generated by clrinf-codegen. DO NOT EDIT.
// </auto-generated>

#nullable enable

namespace ClrInf.Contracts.Stok;

using ClrInf.Contracts;

/// <summary>
/// Event emitted when reserved stock is permanently committed (deducted) after successful payment.
/// </summary>
public sealed record StockCommittedV1(
    /// <summary>Timestamp of commitment</summary>
    DateTimeOffset CommittedAt,
    /// <summary>Identifier of the finalized order</summary>
    string OrderId,
    /// <summary>Committed item count</summary>
    int Quantity,
    /// <summary>Stock keeping unit code</summary>
    string Sku,
    /// <summary>Warehouse code where stock was deducted</summary>
    string Warehouse
) : ICloudEvent
{
    public const string EventTypeName = "com.clrinf.stok.StockCommitted.v1";
    public string EventType => EventTypeName;
}
