// <auto-generated>
// Code generated by clrinf-codegen. DO NOT EDIT.
// </auto-generated>

#nullable enable

namespace ClrInf.Contracts.Stok;

using ClrInf.Contracts;

/// <summary>
/// Event emitted when inventory is reserved for an incoming order.
/// </summary>
public sealed record StockReservedV1(
    /// <summary>Identifier of the order claiming reservation</summary>
    string OrderId,
    /// <summary>Reserved item count</summary>
    int Quantity,
    /// <summary>Stock keeping unit code</summary>
    string Sku,
    /// <summary>Source warehouse code (e.g. IST-01)</summary>
    string Warehouse
) : ICloudEvent
{
    public const string EventTypeName = "com.clrinf.stok.StockReserved.v1";
    public string EventType => EventTypeName;
}
