// <auto-generated>
// Code generated by clrinf-codegen. DO NOT EDIT.
// </auto-generated>

#nullable enable

namespace ClrInf.Contracts.Stok;

using ClrInf.Contracts;

/// <summary>
/// Compensating event emitted when a previously reserved stock allocation is released back to inventory.
/// </summary>
public sealed record StockReleasedV1(
    /// <summary>Identifier of the order whose reservation was released</summary>
    string OrderId,
    /// <summary>Released item count</summary>
    int Quantity,
    /// <summary>Release reason (e.g. PAYMENT_FAILED, TIMEOUT, ORDER_CANCELLED)</summary>
    string Reason,
    /// <summary>Stock keeping unit code</summary>
    string Sku
) : ICloudEvent
{
    public const string EventTypeName = "com.clrinf.stok.StockReleased.v1";
    public string EventType => EventTypeName;
}
