// <auto-generated>
// Code generated by clrinf-codegen. DO NOT EDIT.
// </auto-generated>

#nullable enable

namespace ClrInf.Contracts.Katalog;

using ClrInf.Contracts;

/// <summary>
/// Ürün kataloğuna yeni bir ürün kaydı oluşturma komutu.
/// </summary>
public sealed record UrunOlusturV1(
    /// <summary>Ürün başlığı</summary>
    string Baslik,
    /// <summary>Birim satış fiyatı</summary>
    double BirimFiyat,
    /// <summary>Kategori hiyerarşisi (örn: Elektronik/Sensör/Optik)</summary>
    string KategoriYolu,
    /// <summary>Para birimi kodu (ISO 4217, örn: TRY, USD)</summary>
    string ParaBirimi,
    /// <summary>Stok tutma birimi kodu (benzersiz)</summary>
    string Sku,
    /// <summary>Ürün açıklaması (isteğe bağlı)</summary>
    string? Aciklama = null,
    /// <summary>Ürün varyantları (renk, beden vb.)</summary>
    IReadOnlyList<string>? Varyantlar = null,
    /// <summary>Vergi oranı (0.0 ile 1.0 arasında, örn: 0.18 = %18 KDV)</summary>
    double? Vergiorani = null
)
{
    public const string CommandTypeName = "com.clrinf.katalog.UrunOlustur.v1";
    public string CommandType => CommandTypeName;
}
