// <auto-generated>
// Code generated by clrinf-codegen. DO NOT EDIT.
// </auto-generated>

#nullable enable

namespace ClrInf.Contracts.Katalog;

using ClrInf.Contracts;

/// <summary>
/// Tekil ürün detay sorgusu.
/// </summary>
public sealed record UrunDetayiV1(
    /// <summary>Stok tutma birimi kodu</summary>
    string Sku
)
{
    public const string QueryTypeName = "com.clrinf.katalog.UrunDetayi.v1";
    public string QueryType => QueryTypeName;
}
