// <auto-generated>
// Code generated by clrinf-codegen. DO NOT EDIT.
// </auto-generated>

#nullable enable

namespace ClrInf.Contracts.Katalog;

using ClrInf.Contracts;

/// <summary>
/// Mevcut bir ürünün birim fiyatını güncelleme komutu. Cedar ABAC: FiyatYoneticisi veya YoneticiAdmin rolü gerektirir.
/// </summary>
public sealed record UrunFiyatGuncelleV1(
    /// <summary>Mevcut birim fiyatı (değişiklik öncesi)</summary>
    double EskiFiyat,
    /// <summary>Fiyat güncelleme gerekçesi (denetim izi için zorunlu)</summary>
    string GuncellemeGerekce,
    /// <summary>Para birimi kodu (ISO 4217)</summary>
    string ParaBirimi,
    /// <summary>Stok tutma birimi kodu</summary>
    string Sku,
    /// <summary>Yeni birim fiyatı</summary>
    double YeniFiyat,
    /// <summary>Yeni fiyatın geçerlilik başlangıç tarihi (ISO 8601 UTC)</summary>
    DateTimeOffset? GecerlilikBaslangic = null,
    /// <summary>Yeni fiyatın geçerlilik bitiş tarihi (null ise süresiz)</summary>
    DateTimeOffset? GecerlilikBitis = null
)
{
    public const string CommandTypeName = "com.clrinf.katalog.UrunFiyatGuncelle.v1";
    public string CommandType => CommandTypeName;
}
