// <auto-generated>
// Code generated by clrinf-codegen. DO NOT EDIT.
// </auto-generated>

#nullable enable

namespace ClrInf.Contracts.Katalog;

using ClrInf.Contracts;

/// <summary>
/// Bir ürünün katalogda yayınlandığında yayımlanan olay.
/// </summary>
public sealed record UrunYayinlandiV1(
    /// <summary>Ürün başlığı</summary>
    string Baslik,
    /// <summary>Yayınlama anındaki birim fiyatı</summary>
    double BirimFiyat,
    /// <summary>Kategori hiyerarşisi</summary>
    string KategoriYolu,
    /// <summary>Para birimi kodu (ISO 4217)</summary>
    string ParaBirimi,
    /// <summary>Stok tutma birimi kodu</summary>
    string Sku,
    /// <summary>Ürünün katalogda yayınlandığı tarih (ISO 8601 UTC)</summary>
    DateTimeOffset YayinTarihi,
    /// <summary>Ürün açıklaması</summary>
    string? Aciklama = null,
    IReadOnlyList<string>? Varyantlar = null,
    /// <summary>Vergi oranı</summary>
    double? Vergiorani = null
) : ICloudEvent
{
    public const string EventTypeName = "com.clrinf.katalog.UrunYayinlandi.v1";
    public string EventType => EventTypeName;
}
