// <auto-generated>
// Code generated by clrinf-codegen. DO NOT EDIT.
// </auto-generated>

#nullable enable

namespace ClrInf.Contracts.Auth;

using ClrInf.Contracts;

/// <summary>
/// Event emitted when a new user account is created in the identity service.
/// </summary>
public sealed record UserCreatedV1(
    /// <summary>Creation timestamp</summary>
    DateTimeOffset CreatedAt,
    /// <summary>User primary email address</summary>
    string Email,
    /// <summary>Assigned initial roles</summary>
    IReadOnlyList<string> Roles,
    /// <summary>Unique user identifier (UUID)</summary>
    string UserId
) : ICloudEvent
{
    public const string EventTypeName = "com.clrinf.auth.UserCreated.v1";
    public string EventType => EventTypeName;
}
