// Code generated by clrinf-codegen. DO NOT EDIT.
export interface RecordV1 {
  readonly "displayName": string;
  readonly "enabled": boolean;
  readonly "nested": ReadonlyArray<ReadonlyArray<number>>;
  readonly "payload": Record<string, unknown>;
  readonly "type": string;
  readonly "count"?: number;
  readonly "ratio"?: number;
  readonly "records"?: ReadonlyArray<Record<string, unknown>>;
}

export const RecordV1Type = "test.Record.v1" as const;
export type RecordV1Type = typeof RecordV1Type;
