// @clrinf:generated — TypeScript Module Scaffolding Generator
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

export interface ModuleGeneratorOptions {
  projectRoot: string;
  moduleName: string;
}

function toKebabCase(str: string): string {
  return str
    .replace(/([a-z0-9]|(?=[A-Z]))([A-Z])/g, "$1-$2")
    .toLowerCase()
    .replace(/^-+|-+$/g, "");
}

function toPascalCase(str: string): string {
  return str
    .split(/[-_\s]+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join("");
}

export class ModuleGenerator {
  static async generate(options: ModuleGeneratorOptions): Promise<string[]> {
    const slug = toKebabCase(options.moduleName);
    const pascal = toPascalCase(options.moduleName);
    const createdFiles: string[] = [];

    const modulesRoot = join(options.projectRoot, "src", "modules");
    const moduleDir = join(modulesRoot, slug);
    const rulesDir = join(moduleDir, "rules");

    await mkdir(rulesDir, { recursive: true });

    // 1. models.ts
    const modelsPath = join(moduleDir, "models.ts");
    const modelsContent = `// @clrinf:generated — ${pascal} Domain Models
export interface ${pascal} {
  id: string;
  tenant_id: string;
  created_at: number;
}
`;
    await writeFile(modelsPath, modelsContent);
    createdFiles.push(modelsPath);

    // 2. handlers.ts
    const handlersPath = join(moduleDir, "handlers.ts");
    const handlersContent = `// @clrinf:generated — ${pascal} Handlers and Operation Claims

/**
 * Operation Claim contract for multi-tenant policy evaluation
 */
export interface OperationClaim {
  resource: string;
  action: string;
  resource_tenant_id?: string;
}

export const ${pascal}Claims = {
  create: (tenantId: string): OperationClaim => ({
    resource: "${slug}",
    action: "create",
    resource_tenant_id: tenantId,
  }),
  read: (tenantId: string): OperationClaim => ({
    resource: "${slug}",
    action: "read",
    resource_tenant_id: tenantId,
  }),
  update: (tenantId: string): OperationClaim => ({
    resource: "${slug}",
    action: "update",
    resource_tenant_id: tenantId,
  }),
  delete: (tenantId: string): OperationClaim => ({
    resource: "${slug}",
    action: "delete",
    resource_tenant_id: tenantId,
  }),
};
`;
    await writeFile(handlersPath, handlersContent);
    createdFiles.push(handlersPath);

    // 3. rules/index.ts
    const rulesIndexPath = join(rulesDir, "index.ts");
    const rulesIndexContent = `// @clrinf:generated — ${pascal} Business Rules
// Export business rule functions here.
`;
    await writeFile(rulesIndexPath, rulesIndexContent);
    createdFiles.push(rulesIndexPath);

    // 4. index.ts
    const indexPath = join(moduleDir, "index.ts");
    const indexContent = `// @clrinf:generated — ${pascal} Module Barrel
export * from "./models.js";
export * from "./handlers.js";
export * from "./rules/index.js";
`;
    await writeFile(indexPath, indexContent);
    createdFiles.push(indexPath);

    // 5. Register in src/modules/index.ts
    const parentIndex = join(modulesRoot, "index.ts");
    const exportStatement = `export * as ${pascal}Module from "./${slug}/index.js";\n`;
    try {
      const existing = await readFile(parentIndex, "utf-8");
      if (!existing.includes(exportStatement)) {
        await writeFile(parentIndex, existing + exportStatement);
      }
    } catch {
      await writeFile(parentIndex, `// @clrinf:generated — Modules barrel\n${exportStatement}`);
      createdFiles.push(parentIndex);
    }

    // 6. Multi-Tenant Cedar Policy: policies/<slug>.cedar
    const policiesDir = join(options.projectRoot, "policies");
    await mkdir(policiesDir, { recursive: true });

    const cedarPolicyPath = join(policiesDir, `${slug}.cedar`);
    const cedarContent = `// @clrinf:generated — Multi-Tenant Cedar Policy: ${pascal}
// Generated by clrinfjs scaffold

// 1. PlatformAdmin: Kiracılar arası tam yetki
permit (
    principal in Role::"PlatformAdmin",
    action,
    resource
);

// 2. TenantAdmin: Kendi kiracısındaki ${pascal} kaynaklarında tam yetki
permit (
    principal in Role::"TenantAdmin",
    action,
    resource in ResourceType::"${pascal}"
) when {
    resource.tenant_id == principal.tenant_id
};

// 3. Modül Yöneticisi: Kendi kiracısında tam CRUD yetkisi
permit (
    principal in Role::"${pascal}Manager",
    action in [
        Action::"${slug}.create",
        Action::"${slug}.read",
        Action::"${slug}.update",
        Action::"${slug}.delete"
    ],
    resource in ResourceType::"${pascal}"
) when {
    context.tenant_id == principal.tenant_id &&
    resource.tenant_id == principal.tenant_id
};

// 4. Okuma Rolü: Kendi kiracısında okuma yetkisi
permit (
    principal in Role::"${pascal}Reader",
    action == Action::"${slug}.read",
    resource in ResourceType::"${pascal}"
) when {
    context.tenant_id == principal.tenant_id &&
    resource.tenant_id == principal.tenant_id
};

// 5. Kesin Multi-Tenant İzolasyon Muhafızı (Forbid Guard):
// Kiracı uyuşmazlığı durumunda tüm izin kurallarını ezer ve erişimi engeller
forbid (
    principal,
    action,
    resource in ResourceType::"${pascal}"
) when {
    resource.tenant_id != principal.tenant_id
} unless {
    principal in Role::"PlatformAdmin"
};
`;
    await writeFile(cedarPolicyPath, cedarContent);
    createdFiles.push(cedarPolicyPath);

    return createdFiles;
  }

  async scaffoldModule(options: ModuleGeneratorOptions): Promise<string[]> {
    return ModuleGenerator.generate(options);
  }

  async generate(options: ModuleGeneratorOptions): Promise<string[]> {
    return ModuleGenerator.generate(options);
  }
}
