//! Lightweight, dependency-free source scanning helpers shared by the
//! drift detector (`drift.rs`) and the event impact analyzer (`impact.rs`).
//!
//! The scanner is intentionally heuristic: it matches whole identifiers in
//! `.rs`, `.cs`, `.ts` and `.tsx` files. Generated files (marked with
//! `Code generated by clrinf-codegen`) are reported separately so callers can
//! distinguish hand-written code from codegen output.

use anyhow::Result;
use std::path::{Path, PathBuf};
use walkdir::WalkDir;

const SOURCE_EXTENSIONS: &[&str] = &["rs", "cs", "ts", "tsx"];
const SKIPPED_DIRS: &[&str] = &[
    ".git",
    "node_modules",
    "target",
    "bin",
    "obj",
    "dist",
    ".venv",
    "graft",
];
const GENERATED_MARKER: &str = "Code generated by clrinf-codegen";

#[derive(Debug, Clone)]
pub struct SourceFile {
    pub path: PathBuf,
    pub content: String,
    pub generated: bool,
}

fn is_ident_char(c: char) -> bool {
    c.is_ascii_alphanumeric() || c == '_'
}

/// True when `ident` occurs in `text` delimited by non-identifier characters.
pub fn contains_ident(text: &str, ident: &str) -> bool {
    if ident.is_empty() {
        return false;
    }
    let mut start = 0;
    while let Some(found) = text[start..].find(ident) {
        let begin = start + found;
        let end = begin + ident.len();
        let before_ok = text[..begin].chars().next_back().map_or(true, |c| !is_ident_char(c));
        let after_ok = text[end..].chars().next().map_or(true, |c| !is_ident_char(c));
        if before_ok && after_ok {
            return true;
        }
        start = begin + ident.chars().next().map_or(1, char::len_utf8);
        if start >= text.len() {
            break;
        }
    }
    false
}

/// 1-based line numbers where `ident` occurs as a whole identifier.
pub fn ident_lines(text: &str, ident: &str) -> Vec<usize> {
    text.lines()
        .enumerate()
        .filter(|(_, line)| contains_ident(line, ident))
        .map(|(i, _)| i + 1)
        .collect()
}

/// Load one supported source file (None for unsupported extensions or unreadable files).
pub fn load_source(path: &Path) -> Option<SourceFile> {
    let supported = path
        .extension()
        .and_then(|e| e.to_str())
        .map_or(false, |ext| SOURCE_EXTENSIONS.contains(&ext.to_ascii_lowercase().as_str()));
    if !supported {
        return None;
    }
    let content = std::fs::read_to_string(path).ok()?;
    let generated = content.contains(GENERATED_MARKER);
    Some(SourceFile { path: path.to_path_buf(), content, generated })
}

/// Recursively collect supported source files below `root`.
pub fn collect_sources(root: &Path) -> Result<Vec<SourceFile>> {
    let mut files = Vec::new();
    if !root.exists() {
        return Ok(files);
    }
    let walker = WalkDir::new(root).follow_links(false).into_iter().filter_entry(|entry| {
        if entry.depth() == 0 || !entry.file_type().is_dir() {
            return true;
        }
        entry
            .file_name()
            .to_str()
            .map_or(true, |name| !SKIPPED_DIRS.contains(&name))
    });
    for entry in walker {
        let entry = entry?;
        if !entry.file_type().is_file() {
            continue;
        }
        let supported = entry
            .path()
            .extension()
            .and_then(|e| e.to_str())
            .map_or(false, |ext| SOURCE_EXTENSIONS.contains(&ext.to_ascii_lowercase().as_str()));
        if !supported {
            continue;
        }
        // Skip unreadable / non-UTF8 files rather than failing the whole scan.
        if let Ok(content) = std::fs::read_to_string(entry.path()) {
            let generated = content.contains(GENERATED_MARKER);
            files.push(SourceFile {
                path: entry.path().to_path_buf(),
                content,
                generated,
            });
        }
    }
    files.sort_by(|a, b| a.path.cmp(&b.path));
    Ok(files)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ident_boundaries_are_respected() {
        assert!(contains_ident("await publishOrderPlaced(ctx)", "publishOrderPlaced"));
        assert!(!contains_ident("publishOrderPlacedV2(ctx)", "publishOrderPlaced"));
        assert!(!contains_ident("IOrderPlacedHandler", "OrderPlacedHandler"));
        assert!(contains_ident("class X : IOrderPlacedHandler", "IOrderPlacedHandler"));
        assert!(contains_ident("OrderPlacedHandler", "OrderPlacedHandler"));
    }

    #[test]
    fn ident_lines_are_one_based() {
        let text = "a\nfoo(bar)\nbaz\nbar";
        assert_eq!(ident_lines(text, "bar"), vec![2, 4]);
    }
}
