<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>ClrinfCS.Adapters.Sqlite</PackageId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../ClrinfCS.Core/ClrinfCS.Core.csproj" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="2.1.13" />
  </ItemGroup>
</Project>
