// <auto-generated>
// Code generated by clrinf-codegen. DO NOT EDIT.
// </auto-generated>

#nullable enable

namespace ClrInf.Contracts.Common;

using ClrInf.Contracts;
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
public sealed record RecordV1(
    [property: JsonPropertyName("displayName")]
    string DisplayName,
    [property: JsonPropertyName("enabled")]
    bool Enabled,
    [property: JsonPropertyName("nested")]
    IReadOnlyList<IReadOnlyList<long>> Nested,
    [property: JsonPropertyName("payload")]
    object Payload,
    [property: JsonPropertyName("type")]
    string Type,
    [property: JsonPropertyName("count")]
    int? Count = null,
    [property: JsonPropertyName("ratio")]
    double? Ratio = null,
    [property: JsonPropertyName("records")]
    IReadOnlyList<object>? Records = null
) : ICloudEvent
{
    public const string EventTypeName = "test.Record.v1";
    [JsonIgnore]
    public string EventType => EventTypeName;
}
