// Code generated by clrinf-codegen. DO NOT EDIT.
use serde::{Deserialize, Serialize};
use super::CloudEvent;

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecordV1 {
    #[serde(rename = "displayName")]
    pub display_name: String,
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "nested")]
    pub nested: Vec<Vec<i64>>,
    #[serde(rename = "payload")]
    pub payload: serde_json::Value,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "count")]
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub count: Option<i32>,
    #[serde(rename = "ratio")]
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub ratio: Option<f64>,
    #[serde(rename = "records")]
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub records: Option<Vec<serde_json::Value>>,
}

impl CloudEvent for RecordV1 {
    fn event_type(&self) -> &'static str {
        "test.Record.v1"
    }
}

impl RecordV1 {
    pub const EVENT_TYPE: &'static str = "test.Record.v1";
}
