FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY clrinfcs/ ./clrinfcs/
COPY templates/eticaret-showcase/backend/ ./templates/eticaret-showcase/backend/

WORKDIR /src/templates/eticaret-showcase/backend/src/MigratorApp
RUN dotnet restore MigratorApp.csproj
RUN dotnet publish MigratorApp.csproj -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "MigratorApp.dll"]
